apiVersion: v1
kind: Pod
metadata:
  name: httpd-app
  labels:
    name: httpd-app
spec:
  containers:
  - name: httpd-app
    image: httpd
  - name: centos
    image: centos
    command: ['sleep' ,'6000']