apiVersion: v1
kind: Pod
metadata:
  name: snehal-pod1
spec:
  containers:
  - name: snehal-pod1
    image: httpd:latest
    ports:
      - containerPort: 80
livenessProbe:
  exec:
    command:
      - /bin/my-script.sh
  initialDelaySeconds: 60
  timeoutSeconds: 10