---
apiVersion: v1
kind: ReplicationController
metadata:
  name: snehal-pod1
  labels:
    app: snehal-pod1
spec:
  replicas: 12
  selector:
    app
  containers:
  - name: snehal-pod1
    image: httpd:latest
    ports:
      - containerPort: 80
...
apiVersion: v1
kind: ReplicationController
metadata:
  name: snehal-pod1
spec:
  replicas: 12
  selector:
    app: snehal-pod1
